### ISSUE TITLE
Quote Hover Preview Lag

### ISSUE THREAD

**Issue by saxamaphone69** [saxamaphone69/ss16#30]
Something must have changed recently.
I've noticed in ~200+ post threads that quote previews on hover look like they go under 60fps.
Here is a video highlighting the lag:

https://github.com/user-attachments/assets/a5888205-51e8-4b58-a6fd-2697c17055f7

After deleting random parts of ss21, it seems deleting [CSS related to the new captcha](https://github.com/saxamaphone69/ss21/blob/main/ss21.user.styl#L4270) brings things back to normal:

https://github.com/user-attachments/assets/e3f2e081-ea5e-47b7-bee6-0016e972a0d9

I'm taking a stab at
```css
@css {
		.captcha-container:has(#t-auto-solve:not([style*="none"])) :is(#t-load, #t-resp, #t-auto-solve) {
			width: calc(33% - 0.5rem) !important;
		}
	}
```
Having something to do with it - though when I comment out just that line, nothing happens, so it seems to be a combination of the other selectors and maybe having to `!important` all the inline styles.

**Comment by saxamaphone69** [comment]
```css
#t-cnt:has(#t-fg:not([style*="image"])) {
				display: none !important;
			}
.captcha-container:has(#t-fg:not([style*="image"])) {
			#t-load {
				width: 100% !important;
			}
			#t-resp {
				display: none !important;
			}
		}
.captcha-container:has(#t-auto-solve:not([style*="none"])) :is(#t-load, #t-resp, #t-auto-solve) {
			width: calc(33% - 0.5rem) !important;
		}
```

Yep, commenting these out brings it back to normal. Chucking it into a `@scope` doesn't seem to fix it either.
