### ISSUE TITLE
too many display: none's

### ISSUE THREAD

**Issue by saxamaphone69** [saxamaphone69/ss16#8]
`ss16.user.css` currently has `display: none` written 55 times throughout the userstyle

given the stylelint formatting, this is roughly 1.26KB alone in repeated declarations

```css
.hi {
  display: none;
}

.hi {
  display: none;
}
```

using csso (which brings it to a single declaration, albeit without whitespaces, and not accounting for longer selectors) brings it down to 17B

```css
.hi{display:none}
```

just wondering if the trade off for size is affected by the tradeoff for (potential) speed
